In [ ]:
import pandas as pd
import tensorflow as tf

!pip install tensorflow-io
import tensorflow_io as tfio

     |████████████████████████████████| 25.3MB 178kB/s 


In [ ]:
tfio.audio.AudioIOTensor

tensorflow_io.core.python.ops.audio_ops.AudioIOTensor

In [ ]:
def _string2int(text, alphabet_size = 26, first_letter=96):
   text = [ord(letter)-first_letter for letter in text ]
   for i in range(len(text)):
    if text[i] == -50: # -50 = . dot
      text[i] = alphabet_size+1

    if text[i] == -52: # -50 = , comma
      text[i] = alphabet_size+2

   return text

In [ ]:
def _padd(texts):
  return tf.keras.preprocessing.sequence.pad_sequences(texts, maxlen=None,
                                                       dtype='int32', padding='post', value=0.0)

In [ ]:
def _one_hot_encode(texts, comma=False, alphabet_size = 26, first_letter=96):
  
  # text = tf.convert_to_tensor(text)
  # if comma:
  # alphabet size = 26 + 1 (dot) + 1 pad
  depth = alphabet_size+3 if comma else alphabet_size+2

  # print(depth)
  return tf.one_hot(texts, depth=depth, axis=2)#, text
  # return text

In [ ]:
batch = ["az.,",
         "tyf",
         "mnhyrtfh"]
int_batch = []

for i in batch:
  int_batch.append(string2int(i))

int_batch = padd(int_batch)

print(int_batch)

print( _one_hot_encode(int_batch, comma=True))

[[ 1 26 27 28  0  0  0  0]
 [20 25  6  0  0  0  0  0]
 [13 14  8 25 18 20  6  8]]
tf.Tensor(
[[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 1.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
   0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [ ]:
def load_cleaning_pipeline(src, data):
  1- loads the wav
  2- clean wav
  3- clean text
  
  data = data.map(lambda x: data_load.load_wav(src, x))
  data = data.map(data_clean.clean_wav)
  data = data.map(data_clean.clean_text)

In [ ]:
def select_x_y(data, x, y):
   return (data[x], data[y])

In [ ]:
def load_split_data():
  dataset = data.load(src, splits, remove_organized_path=False, download=True)
  train = dataset[dataset["split"]=="train"]
  dev   = dataset[dataset["split"]=="dev"]
  test  = dataset[dataset["split"]=="test"]
  
  return train, dev, test 

In [ ]:
def pipeline(src, split, x, y):
  1- load_cleaning_pipeline
  2- select_x_y
   a- string to list of ints 
  3- batch
  4- parallel ... etc

  4- one hot encode text
    a- 
    c- padd
    d- _one_hot_encode

  split = load_cleaning_pipeline(src, data=split)
  split, text_position = select_x_y(data, x, y)
  split = _string2int(text, alphabet_size = 26, first_letter=96)
  split = batch
  split = padd
  split = _one_hot_encode


  return train, dev, test

In [ ]:
def text2audio_pipeline():
  return pipeline(x.y) #set x,y

In [ ]:
def test(x, y):
  return x+y

def wr(**kwargs):
  return test(**kwargs)

In [ ]:
wr(x=5, y=10)

15

In [ ]:
data = pd.DataFrame({
    "id":[1, 2, 3, 4],

    "tst1":[5,4,3,7],
    "tst2":[5,4,3,7]
}).set_index("id")

In [ ]:
data

tst1  tst2
id            
1      5     5
2      4     4
3      3     3
4      7     7

In [ ]:
data.reset_index(inplace=True)
data

id  tst1  tst2
0   1     5     5
1   2     4     4
2   3     3     3
3   4     7     7

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices(data)

In [ ]:
for x in dataset.take(3):
  print (x)

tf.Tensor([1 5 5], shape=(3,), dtype=int64)
tf.Tensor([2 4 4], shape=(3,), dtype=int64)
tf.Tensor([3 3 3], shape=(3,), dtype=int64)


In [ ]:
def ds(x, y):
  return tf.convert_to_tensor([x[0]*y, x[1], x[2]], dtype=tf.int64)

In [ ]:
dataset = dataset.map(lambda x: ds(x,6))

In [ ]:
for x in dataset.take(3):
  print (x)

tf.Tensor([6 5 5], shape=(3,), dtype=int64)
tf.Tensor([12  4  4], shape=(3,), dtype=int64)
tf.Tensor([18  3  3], shape=(3,), dtype=int64)


In [ ]:
def ds2(x):
  return (x[0:2], x[1:2])

In [ ]:
dataset = dataset.map(ds2)

In [ ]:
for x in dataset.take(3):
  print (x)

(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([5, 5])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([5])>)
(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([10,  4])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([4])>)
(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([15,  3])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([3])>)
